### ISSUE TITLE
Rewrite Status

### ISSUE THREAD

**Issue by tivac** [lhorie/mithril.js#1090]
Let's have a single place to track the rewrite status!

(As best as I can figure it at least, some things are still just stored in @lhorie's head :smile:)

## Alpha

- [x] Test runner
- [x] Bundling script
- [x] DOM diffing
- [x] Hyperscript API
- [x] Lifecycle methods
- [x] `v0.2.x`-style API
- [x] Rate-limit redraws when mounted
- [x] prevent redraws from event handlers
- [x] basic `m.prop()` support (currently without promise absorbing behavior. Still undecided if that behavior is staying)
- [x] Promise polyfill
- [x] [`v0.2.x` :arrow_right: `v1.x` Migration Guide](https://github.com/lhorie/mithril.js/blob/rewrite/docs/v1.x-migration.md)
- [ ] **maybe** - `m.startComputation()` & `m.endComputation()`
- [ ] `shouldUpdate` :arrow_right: `onbeforeupdate` ([discussion](https://gitter.im/lhorie/mithril.js?at=5745d76f6bbc2d1d4dee12b0))
- [ ] Tests for `contenteditable`, custom elements, DOM recycling w/ components
- [ ] **maybe** - #1014 Don't output booleans from hyperscript API
- [ ] ES6 classes as components
- [ ] #1044 - Determine final public API both for all-in-one consumption (`require("mithril")`) and piecemeal consumption (`require("mithril/route")`)

## Beta

- [ ] IE perf improvements from https://github.com/lhorie/mithril.js/pull/1016

**NOTE**: This isn't an issue for discussing API design/rewrite bugs/etc, those should happen in their own more focused issues.

**Comment by isiahmeadows** [comment]
@tivac @lhorie I added a `rewrite` milestone to help better categorize things, and I've added them to several existing issues. Welcome.

**Comment by nordfjord** [comment]
@lhorie would love to see more "Array" methods on the streams.

e.g. forEach, filter, reduce

```
let userStream = m.prop()
  .filter(user => user.isVisibleOnline)
  .forEach(user => {
    displayUserLoginPopup(user);
  });

subscribeToUserChannel(userStream);
```

**Comment by tinchoz49** [comment]
Yes i aggree with @nordfjord and maybe if the streams has an API compatible for example with the [flyd streams](https://github.com/paldepind/flyd#api) we can extend the methods using their modules (filter, lift, flatmap...) without increase the size and the API stream functions in mithril.

BTW: great idea add the stream support. :+1:  :rocket:

**Comment by darsain** [comment]
@lhorie if it's a breaking change already, why make it ambiguous by still calling it `m.prop`? Just name it `m.stream` :)

**Comment by pietermartin** [comment]
Any more info regarding the status of the rewrite.
We are planning on rewriting a large Angular 1 app and Mithril looks great but alas the status?

**Comment by lhorie** [comment]
@pietermartin it's currently at release candidate 2

**Comment by lhorie** [comment]
update: taking these out:

 ```
- [ ] #618 - ES6 classes as components
- [ ] `m.startComputation()` & `m.endComputation()`
```

**Comment by finetype** [comment]
Migration guide link is dead.
link to docs for m.prop discussing breaking change to streams is dead.

**Comment by gyandeeps** [comment]
"IE perf improvements" was marked done but I don't see it in the code. Am I missing something or was it dropped from the plan?

**Comment by tivac** [comment]
@gyandeeps Hmm, might've gotten lost in a re-shuffle. Would you be willing to open a new PR? 😞

**Comment by gyandeeps** [comment]
@tivac I am loaded with work currently, i can when i get some time but meanwhile if somebody else wnat to do it feel free.

More details:

Here is the previous PR: https://github.com/lhorie/mithril.js/pull/1016
Issue comment: https://github.com/lhorie/mithril.js/issues/199#issuecomment-210110023

This should give enough information. 

Theme: **Add the element to its parent before you add its children to it**. this has perf imrovments on IE engines.

**Comment by gyandeeps** [comment]
@tivac Spent some time today to get this work: https://github.com/lhorie/mithril.js/pull/1598

**Comment by lhorie** [comment]
added some love for @gyandeeps : http://mithril.js.org/credits.html
