### ISSUE TITLE
Mithril.js Bucket List

### ISSUE THREAD

**Issue by isiahmeadows** [lhorie/mithril.js#802]
**Do subscribe to this to keep updated! I do try to keep this up to date!**

This is a meta bug for some of the more prominent proposals that haven't been rejected. Discussion on any of these ideas specifically are better left on the relevant sub-bug of this one. Being on this list does not guarantee it'll be in the next version of Mithril.

If I missed anything, a new bug was opened for something on this list, or if something else comes up, please tell me. Just make sure to @mention me so I'll know about it and can update this accordingly.

- [x] a. Modularize the source code somehow. #651, #665 (PR itself dead)

- [ ] b. Use classes as components (ES6, TypeScript, CoffeeScript, etc.). #618 

- [x] c. `m.deferred()`/`m.sync()` &rarr; `new Promise()`/`Promise.all()`. #800 

  This will add a single dependency for a compliant ES6 or Promises/A+ Promise implementation, only for `m.request` and `m.prop(thenable)`. The old forms will be deprecated, and this will be a breaking change.

- [ ] d. `m.prop()` should be a little less infectious. [#800 (comment)](https://github.com/lhorie/mithril.js/issues/800#issuecomment-158235807)

- [x] e. Lint the source, likely with ESLint. #706 **(Merged in #822, #828, #973)**

- [x] f. Use a real testing framework for [all the tests](https://github.com/lhorie/mithril.js/blob/next/tests/mithril-tests.js) & unify with QUnit tests. #801 **(Merged in #822)**

- [ ] g. Partial rendering. #291, related to #538 

- [ ] h. Iterables as template arguments. #517 

Some of these were mostly discussed in the [Gitter room](https://gitter.im/lhorie/mithril.js), while others originated in other bugs.

/cc @lhorie (You're welcome in advance.)

**Comment by impinball** [comment]
I also know this is probably not the best of titles, so if you have something better, please share. I'll probably take it.

**Comment by lhorie** [comment]
@impinball  A few other ones off the top of my head:

- partial rendering
- class sugar (e.g. `{class: {foo: shouldFooAppear}}` )
- generator support
- HTML namespace support

**Comment by tinchoz49** [comment]
hi guys! @lhorie i think the class sugar can be defined as an external module or maybe better simple use [classnames](https://github.com/JedWatson/classnames) 
```js
{
  class: classnames({

  })
}

```

**Comment by andre-gh** [comment]
The ability to re-render only specific components as needed would be hugely helpful for integration with third party libraries which take ownership of the DOM.

As it is now you need to wrap a component inside a component which `render`s the other component inside a `config`.

**Comment by andre-gh** [comment]
For example, say I have a library which sorts, filters, paginates tables etc (like `datatables`).  I can use a mithriljs component to render out that table beautifully and then use `config` to pass that table off to the library.  However, from that point on if I want to re-render that table I have to re-render the entire page (say for example, I have a mithril-driven dropdown to change which animal specifies I am looking at as a whole, and this table is a small widget within the page as a whole, or I have multiple of them on the page, etc).

**Comment by impinball** [comment]
As soon as I get to a computer, I'll update.

**Comment by impinball** [comment]
Updated!

**Comment by impinball** [comment]
Updated! (recent patch)

**Comment by impinball** [comment]
Updated! (recent patch & Gitter discussion)

**Comment by barneycarroll** [comment]
> * generator support

@lhorie generators are a language feature, the onus on support is in the runtime environment. Where do you see these being involved in Mithril?

**Comment by lhorie** [comment]
@barneycarroll someone had mentioned that it would be nice to support them in templates, e.g. 

```
m("ul", liGenerator) //render a bunch of <li>'s
```

It's more of a nice-to-have than anything else, and not a huge priority

**Comment by impinball** [comment]
@lhorie would you be okay with later making components be able to return
arrays?

**Comment by lhorie** [comment]
@impinball yeah I'd like to make that work at some point

**Comment by impinball** [comment]
Removing "CSS class object (string-boolean hash maps)", as they [appear to be losing support there](https://github.com/lhorie/mithril.js/issues/545#issuecomment-144470733) in favor of [classnames](http://npm.im/classnames).

**Comment by tinchoz49** [comment]
@impinball i agree!

**Comment by impinball** [comment]
Updated

**Comment by impinball** [comment]
Updated!

**Comment by impinball** [comment]
Updated!

**Comment by lhorie** [comment]
linting and m.prop promise infectiousness were reverted in 0.2.2-rc.1, so I'm unchecking those items

**Comment by isiahmeadows** [comment]
I'm fine with that.

**Comment by lhorie** [comment]
Going to close this in favor of #1090
